### PR TITLE
Generate approximate mask of spinal cord

### LINKED ISSUE #71: Generate an approximate spinal cord mask for the phantom data
Proposed strategy:
- Identify a reference site
- Identify a reference image
- Generate an approximate mask of the spinal cord on the phantom for this site
- Register the reference image from site _i_ to the reference site https://github.com/spinal-cord-7t/coil-qc-code/issues/72
- Apply the inverse transformation to the mask (using trilinear interpolation).

Related to #63

### PR DESCRIPTION
**Pull request by jcohenadad**
Method to generate approximate spinal cord is illustrated below:

Screenshot 2024-06-08 at 11 13 37 PM

The source of the figure is available here: [phantom_mask_creation.zip](https://github.com/user-attachments/files/15750425/phantom_mask_creation.zip)

Fixes #71

### CODE REVIEW

**Comment by evaalonsoortiz** [comment]
Looks good. I've pushed some changes : https://github.com/spinal-cord-7t/coil-qc-code/commit/6550f393643c09088c4d4249aa964c4064ee5883 after which I will merge.

**Comment by evaalonsoortiz** [comment]
After merging this PR I picked up an error. The code starting here: https://github.com/spinal-cord-7t/coil-qc-code/blob/5a5786bd7efa9d39fbfaeb0f2f8076fab2587732/data_processing-phantom.ipynb#L328

assumes that {subject_ref}_acq-famp_TB1TFL_label.nii.gz already exists, but it hasn't been created.

**Comment by evaalonsoortiz** [comment]
The problem is now fixed in: https://github.com/spinal-cord-7t/coil-qc-code/commit/d9efe5843f2089d277e6197f0de54307378ac173

**Comment by jcohenadad** [comment]
> After merging this PR I picked up an error. The code starting here:

great catch! thank you for fixing this

**Pull request merged**
