### PR TITLE
Convert notebook to jupyter books with outputs and host on GitHub pages

### PR DESCRIPTION
**Pull request by jcohenadad**
Notebooks visible at: https://spinal-cord-7t.github.io/coil-qc-code

Fixes https://github.com/spinal-cord-7t/coil-qc-code/issues/126

### CODE REVIEW

**Comment by jcohenadad** [comment]
Hum... I'm trying to re-run the GHA to use the latest notebook available on the main branch, but the built JB on GH page is still the same. It's probably something very simple, @mathieuboudreau can you let me know how to do it? Thank you

**Comment by jcohenadad** [comment]
> Hum... I'm trying to re-run the GHA to use the latest notebook available on the main branch, but the built JB on GH page is still the same. It's probably something very simple, @mathieuboudreau can you let me know how to do it? Thank you

ah, maybe this is because there was an error in execution:

https://github.com/spinal-cord-7t/coil-qc-code/actions/runs/11630302881/job/32446074770?pr=152#step:8:43

**Comment by mathieuboudreau** [comment]
> > Hum... I'm trying to re-run the GHA to use the latest notebook available on the main branch, but the built JB on GH page is still the same. It's probably something very simple, @mathieuboudreau can you let me know how to do it? Thank you
> 
> ah, maybe this is because there was an error in execution:
> 
> https://github.com/spinal-cord-7t/coil-qc-code/actions/runs/11630302881/job/32446074770?pr=152#step:8:43

No, its because i changed the build mode in such a way that only builds from my branch would get hosted on the gh-pages (otherwise while testing it for you, any pushes by you would have “replaced” mine and be a pain). I’ll start a Pr now so that master starts using my current jupiter book builds - sorry for the confusion

**Comment by mathieuboudreau** [comment]
Ahh haha i just saw that this was the PR you made for that purpose, woops.  Let me check if ur hunch was correct instead

**Comment by mathieuboudreau** [comment]
@jcohenadad the builds are only building my current branch, not the "merged" state, and my branch's notebooks haven't been updated since I first created it, i.e. the reason the built JB are showing the old notebooks is because only the old notebooks are in my branch.

If/when you merged this PR, the next main branch build should build the latest version of that notebook that's currently in master. If you'd rather test it through my branch first, we could copy the latest notebooks to my branch first and see the build there before merging

**Comment by jcohenadad** [comment]
> the reason the built JB are showing the old notebooks is because only the old notebooks are in my branch.

ah! that explains it. So me relaunching the GHA is useless then 😅 

> If/when you merged this PR, the next main branch build should build the latest version of that notebook that's currently in master. If you'd rather test it through my branch first, we could copy the latest notebooks to my branch first and see the build there before merging

at this point (ie ismrm deadline in 3d, with Eva needing to get the figure by tmr ideally) i would go with the simplest approach -- so i guess we should merge then?

**Comment by mathieuboudreau** [comment]
>i would go with the simplest approach -- so i guess we should merge then?

Yep, no merge conflicts, I didn't touch the notebooks besides adding tags, so merging!

**Comment by mathieuboudreau** [comment]
Build initiated, here's the one to keep an eye one: https://github.com/spinal-cord-7t/coil-qc-code/actions/runs/11655795073/job/32450980690

**Pull request merged**
